"use client"
import { useState } from 'react'
import { AlertCircle, X } from 'lucide-react'

interface TermsModalProps {
  isOpen: boolean
  onClose: () => void
  onAccept: () => void
}

export default function TermsModal({ isOpen, onClose, onAccept }: TermsModalProps) {
  const [acceptedTerms, setAcceptedTerms] = useState({
    dataProcessing: false,
    contentRights: false,
    aiDisclaimer: false,
    prohibitedUse: false,
    ageConfirmation: false
  })

  const allTermsAccepted = Object.values(acceptedTerms).every(value => value === true)

  const handleCheckboxChange = (term: keyof typeof acceptedTerms) => {
    setAcceptedTerms(prev => ({
      ...prev,
      [term]: !prev[term]
    }))
  }

  if (!isOpen) return null

  return (
    <div className="fixed inset-0 backdrop-blur-sm bg-opacity-50 z-50 flex items-center justify-center p-4">
      <div className="bg-white rounded-lg shadow-xl w-full max-w-md max-h-[90vh] overflow-y-auto">
        <div className="p-5 border-b border-gray-200 flex justify-between items-center sticky top-0 bg-white">
          <h3 className="text-xl font-bold text-purple-800 flex items-center">
            <AlertCircle className="w-5 h-5 mr-2 text-purple-600" />
            Avatar AI Terms & Conditions
          </h3>
          <button
            onClick={onClose}
            className="text-gray-500 hover:text-gray-700 transition-colors"
          ><X className="w-5 h-5" />
          </button>
        </div>

        <div className="p-5 space-y-6">
          <div className="text-gray-600 text-sm">
            <p className="mb-4">
              Before generating your talking head video, please review and accept the following terms and conditions:
            </p>

            <div className="bg-purple-50 p-4 rounded-md border border-purple-200 mb-4">
              <h4 className="font-semibold text-purple-800 mb-2">Data Processing Agreement</h4>
              <p className="text-sm mb-2">
                By using Avatar AI, you consent to our processing of your uploaded content (reference images, voice recordings, and text) 
                for the purpose of generating synthetic talking head videos. Your data will be processed using our AI technologies to create 
                personalized content that matches your inputs.
              </p>
              <p className="text-sm">
                All uploaded data is temporarily stored on our secure servers during processing and is automatically deleted after 30 days, 
                unless you request earlier deletion or extended storage.
              </p>
            </div>

            <div className="bg-purple-50 p-4 rounded-md border border-purple-200 mb-4">
              <h4 className="font-semibold text-purple-800 mb-2">Content Rights & Usage</h4>
              <p className="text-sm mb-2">
                You retain all ownership rights to your original uploaded content. By using our service, you grant Avatar AI a non-exclusive, 
                worldwide license to use, store, and process your content solely for the purpose of providing and improving our services.
              </p>
              <p className="text-sm">
                You are solely responsible for ensuring you have all necessary rights, permissions, and consents for any content you upload, 
                including but not limited to reference images, voice recordings, and text inputs. Do not upload images or voice recordings of 
                other people without their explicit consent.
              </p>
            </div>

            <div className="bg-purple-50 p-4 rounded-md border border-purple-200 mb-4">
              <h4 className="font-semibold text-purple-800 mb-2">AI-Generated Content Disclaimer</h4>
              <p className="text-sm mb-2">
                The talking head videos generated by our service are synthetic AI creations and do not represent real individuals or their actual statements. 
                You agree to use generated content responsibly and to clearly disclose its AI-generated nature when sharing.
              </p>
              <p className="text-sm">
                Avatar AI cannot guarantee perfect synchronization, natural movement, or flawless results in all cases. Quality may vary based on the 
                quality of your input materials and technical limitations of current AI technologies.
              </p>
            </div>

            <div className="bg-purple-50 p-4 rounded-md border border-purple-200 mb-4">
              <h4 className="font-semibold text-purple-800 mb-2">Prohibited Uses</h4>
              <p className="text-sm mb-2">
                You agree not to use our service to create content that is illegal, fraudulent, deceptive, defamatory, harassing, hateful, obscene, 
                or that violates the rights of any third party. This includes but is not limited to:
              </p>
              <ul className="list-disc pl-5 text-sm space-y-1">
                <li>Deepfakes intended to deceive or manipulate</li>
                <li>Content that impersonates individuals without permission</li>
                <li>Misinformation or political manipulation</li>
                <li>Content that promotes discrimination or violence</li>
                <li>Adult, explicit, or inappropriate content</li>
              </ul>
            </div>

            <div className="bg-purple-50 p-4 rounded-md border border-purple-200">
              <h4 className="font-semibold text-purple-800 mb-2">Age Confirmation</h4>
              <p className="text-sm">
                You confirm that you are at least 16 years old and, if required by your local laws, have parental consent 
                to use this service and provide your data. Avatar AI is not intended for use by individuals under the applicable 
                minimum age in their jurisdiction.
              </p>
            </div>
          </div>

          <div className="space-y-4 pt-2">
            <div className="flex items-start">
              <input
                type="checkbox"
                id="dataProcessing"
                checked={acceptedTerms.dataProcessing}
                onChange={() => handleCheckboxChange('dataProcessing')}
                className="mt-1 mr-3 h-4 w-4 rounded border-gray-300 text-purple-600 focus:ring-purple-500"
              />
              <label htmlFor="dataProcessing" className="text-sm text-gray-700">
                I agree to the Data Processing terms and understand how my uploaded content will be used and stored.
              </label>
            </div>

            <div className="flex items-start">
              <input
                type="checkbox"
                id="contentRights"
                checked={acceptedTerms.contentRights}
                onChange={() => handleCheckboxChange('contentRights')}
                className="mt-1 mr-3 h-4 w-4 rounded border-gray-300 text-purple-600 focus:ring-purple-500"
              />
              <label htmlFor="contentRights" className="text-sm text-gray-700">
                I confirm I have all necessary rights and permissions for the content I upload, and I accept the Content Rights & Usage terms.
              </label>
            </div>

            <div className="flex items-start">
              <input
                type="checkbox"
                id="aiDisclaimer"
                checked={acceptedTerms.aiDisclaimer}
                onChange={() => handleCheckboxChange('aiDisclaimer')}
                className="mt-1 mr-3 h-4 w-4 rounded border-gray-300 text-purple-600 focus:ring-purple-500"
              />
              <label htmlFor="aiDisclaimer" className="text-sm text-gray-700">
                I understand that the generated videos are AI-created synthetic content and will use them responsibly with appropriate disclosure.
              </label>
            </div>

            <div className="flex items-start">
              <input
                type="checkbox"
                id="prohibitedUse"
                checked={acceptedTerms.prohibitedUse}
                onChange={() => handleCheckboxChange('prohibitedUse')}
                className="mt-1 mr-3 h-4 w-4 rounded border-gray-300 text-purple-600 focus:ring-purple-500"
              />
              <label htmlFor="prohibitedUse" className="text-sm text-gray-700">
                I agree not to use this service for any prohibited purposes, including deception, impersonation, or creating inappropriate content.
              </label>
            </div>

            <div className="flex items-start">
              <input
                type="checkbox"
                id="ageConfirmation"
                checked={acceptedTerms.ageConfirmation}
                onChange={() => handleCheckboxChange('ageConfirmation')}
                className="mt-1 mr-3 h-4 w-4 rounded border-gray-300 text-purple-600 focus:ring-purple-500"
              />
              <label htmlFor="ageConfirmation" className="text-sm text-gray-700">
                I confirm I am at least 16 years old or have parental consent to use this service.
              </label>
            </div>
          </div>
        </div>

        <div className="p-5 border-t border-gray-200 flex justify-end gap-3 sticky bottom-0 bg-white">
          <button
            onClick={onClose}
            className="px-4 py-2 border border-gray-300 rounded-md text-gray-700 hover:bg-gray-50 transition-colors"
          >Cancel
          </button>
          <button
            onClick={onAccept}
            disabled={!allTermsAccepted}
            className={`px-4 py-2 rounded-md text-white transition-colors ${
              allTermsAccepted
                ? 'bg-purple-600 hover:bg-purple-700'
                : 'bg-purple-300 cursor-not-allowed'
            }`}
          >Accept & Continue
          </button>
        </div>
      </div>
    </div>
  )
}